### ISSUE TITLE
Support for austin

### ISSUE THREAD

**Issue by mgedmin** [laixintao/flameshow#76]
[Austin](https://github.com/P403n1x87/austin) produces profiles compatible with flamegraph.pl, but flameshow is unable to handle them:

> flameshow.exceptions.ProfileParseException: Can not match any parser

I was hoping to play with flameshow because Austin's own austin-tui is a bit limited.

I'm attaching a sample profile for reference (gzipped, because GitHub didn't let me attach the 3 MB file directly):
[austin_1729853732_245906.aprof.txt.gz](https://github.com/user-attachments/files/17521061/austin_1729853732_245906.aprof.txt.gz)

**Comment by laixintao** [comment]
Thanks for telling me this!

I downloaded your sample (thanks again for posting file), seems that the austin file starts with some comments:

```
# austin: 3.7.0
# interval: 100
# mode: wall
# python: 3.12.7
# duration: 828637
# sampling: 3,35,6057
# saturation: 39/5305
# errors: 820/5305
```

After manually remove those I am able to open it work with flameshow.

I will let flameshow handle the opening comments so that you don't need to manually remove it.

**Comment by laixintao** [comment]
Hi @mgedmin 

It's supported now! can try to upgrade to v1.1.3

<img width="1705" alt="image" src="https://github.com/user-attachments/assets/1ae4c7d7-c923-4b46-8b34-0a23baee7fea">

**Comment by mgedmin** [comment]
Amazing!  Thank you for the quick fix!
